SRC/SRC/urls.py
from django.contrib import admin
from django.urls import path, include
from lms import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name="home"),  # Home page

    # User Authentication
    path('user_registration/', views.user_registration, name="user_registration"),
    path('login/', views.login, name="login"),
    path('logout/', views.logout_view, name="logout"),

    # Course Management
    path('course_info/', views.course_info, name="course_info"),
    path('course_details/<str:course_slug>/', views.course_details, name="course_details"),
    path('course_basic_details/<str:course_slug>/', views.course_basic_details, name="course_basic_details"),

    # Trainer Management
    path('trainer_registration/', views.trainer_registration, name="trainer_registration"),
    path('learn_as_trainer/', views.learn_as_trainer, name="learn_as_trainer"),

    # Include LMS URLs
    path('lms/', include(('lms.urls', 'lms'), namespace='lms')),  # Include LMS app's URLs
    path('', views.home, name='home'),
    path('user_registration/', views.user_registration, name='user_registration'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('course_info/', views.course_info, name='course_info'),
    path('course_details/<slug:course_slug>/', views.course_details, name='course_details'),
    path('course_basic_details/<slug:course_slug>/', views.course_basic_details, name='course_basic_details'),
    path('trainer_registration/', views.trainer_registration, name='trainer_registration'),
    path('learn_as_trainer/', views.learn_as_trainer, name='learn_as_trainer'),
    path('register_as_trainer/', views.register_as_trainer, name='register_as_trainer'),
    path('dashboard/', views.dashboard, name='dashboard'),  # Ensure this URL pattern is included
]

SRC/lms/urls.py
from django.urls import path
from . import views

app_name = 'lms'

urlpatterns = [
    path('', views.home, name='home'),
    path('user_registration/', views.user_registration, name='user_registration'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('course_info/', views.course_info, name='course_info'),
    path('course_details/<slug:course_slug>/', views.course_details, name='course_details'),
    path('course_basic_details/<slug:course_slug>/', views.course_basic_details, name='course_basic_details'),
    path('trainer_registration/', views.trainer_registration, name='trainer_registration'),
    path('learn_as_trainer/', views.learn_as_trainer, name='learn_as_trainer'),
    path('register_as_trainer/', views.register_as_trainer, name='register_as_trainer'),
    path('dashboard/', views.dashboard, name='dashboard'),  # Ensure this URL pattern is included
]

SRC/lms/models.py
from django.db import models
from django.db.models.signals import pre_save
from django.contrib.auth.models import User

class TrainerRegistration(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    status = models.BooleanField()

    def __str__(self):
        return self.user.first_name
    
class CourseInfo(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    course_name = models.CharField(max_length=1000)
    slug = models.SlugField(max_length=250, null=True, blank=True)
    course_category = (
        ('development', 'Development'),
        ('business', 'Business'),
        ('finance & accounting', 'Finance & Accounting'),
        ('it & software', 'IT & Software'),
        ('marketing', 'Marketing'),
    )
    category = models.CharField(max_length=1000, choices=course_category, default='development')

    def __str__(self):
        return self.course_name

def course_slug(instance):
    return instance.course_name.lower().replace(' ', '-')

def course_slug_generator(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = course_slug(instance)




pre_save.connect(course_slug_generator, sender=CourseInfo)

class CourseDetails(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    course_info = models.ForeignKey(CourseInfo, on_delete=models.CASCADE)
    course_image = models.ImageField(blank=True, null=True)
    course_desc = models.TextField()

SRC/lms/forms.py
from lms.models import *
from django import forms

class CourseInfoForm(forms.ModelForm):
    class Meta:
        model = CourseInfo
        fields = "__all__"
        # widgets = {'user': forms.HiddenInput(), 'slug': forms.HiddenInput()}

class CourseDetailsForm(forms.ModelForm):
    class Meta:
        model = CourseDetails
        fields = "__all__"

SRC/lms/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import User,auth
from django.contrib import messages
from .forms import CourseInfoForm, CourseDetailsForm
from .models import CourseInfo, CourseDetails, TrainerRegistration
from django.http import HttpResponseRedirect
from django.urls import reverse

def course_info(request):
    user = request.user

    if request.method == 'POST':
        form = CourseInfoForm(request.POST, request.FILES)
        if form.is_valid():  # Form cleaning & Validation
            new_course = form.save()
            return HttpResponseRedirect(reverse('course_details.html', args=(new_course.slug,)))

    form = CourseInfoForm(initial={"user": user})

    course_info = CourseInfo.objects.filter(user=user)
    course_details = CourseDetails.objects.filter(user=user)
    trainer_registration_details = TrainerRegistration.objects.filter(user=user)

    for details in trainer_registration_details:
        if details.status:
            context = {
                "form": form,
                "course_info": course_info,
                "course_details": course_details,
            }
            return render(request, 'course_info.html', context)
        else:
            return render(request, 'learn_as_trainer.html')

def course_details(request, course_slug):
    course_info = CourseInfo.objects.get(slug=course_slug)

    context = {
        "course_slug": course_slug,
        "course_info": course_info,
    }
    return render(request, 'course_details.html', context)

def course_basic_details(request, course_slug):
    user = request.user
    course_info = CourseInfo.objects.get(slug=course_slug)

    if request.method == 'POST':
        form = CourseDetailsForm(request.POST, request.FILES)
        if form.is_valid():  # Form cleaning & Validation
            form.save()
            return HttpResponseRedirect(reverse('course_details.html', args=(course_slug,)))

    form = CourseDetailsForm(initial={'course_info': course_info, 'user': user})

    context = {
        "course_slug": course_slug,
        "course_info": course_info,
        "form": form,
    }
    return render(request, 'course_basic_details.html', context)

def home(request):
    return render(request, 'home.html')

def user_registration(request):
    if request.method == 'POST':
        first_name = request.POST.get("first_name")
        last_name = request.POST.get("last_name")
        user_name = request.POST.get("user_name")
        email = request.POST.get("email")
        mobile = request.POST.get("mobile")
        password1 = request.POST.get("password1")
        password2 = request.POST.get("password2")

        if User.objects.filter(username=user_name).exists():
            messages.error(request, 'Username Taken')
            return redirect('user_registration.html')
        elif User.objects.filter(email=email).exists():
            messages.error(request, 'Email Taken')
            return redirect('user_registration.html')
        elif password1 != password2:
            messages.error(request, 'Passwords do not match')
            return redirect('user_registration.html')
        else:
            user = User.objects.create_user(
                username=user_name,
                first_name=first_name,
                last_name=last_name,
                email=email,
                password=password1
            )
            user.save()
            messages.success(request, 'User registered successfully')
            return redirect('login.html')
    else:
        return render(request, 'user_registration.html')

def login(request):
    if request.method == 'POST':
        user_name = request.POST.get("user_name")
        password = request.POST.get("password")

        user = auth.authenticate(username=user_name, password=password)
        if user is not None:
            auth.login(request, user)
            return redirect('dashboard.html')
        else:
            messages.error(request, 'Invalid credentials')
            return redirect('login.html')
    else:
        return render(request, 'dashboard.html')

def logout(request):
    auth.logout(request)
    return redirect('')

def trainer_registration(request):
    if request.method == 'POST':
        first_name = request.POST.get("first_name")
        last_name = request.POST.get("last_name")
        user_name = request.POST.get("user_name")
        email = request.POST.get("email")
        mobile = request.POST.get("mobile")
        password1 = request.POST.get("password1")
        password2 = request.POST.get("password2")

        if password1 != password2:
            messages.error(request, 'Passwords do not match')
            return redirect('trainer_registration.html')
        elif User.objects.filter(username=user_name).exists():
            messages.info(request, 'Username Taken')
            return redirect('trainer_registration.html')
        elif User.objects.filter(email=email).exists():
            messages.info(request, 'Email Taken')
            return redirect('trainer_registration.html')
        else:
            user = User.objects.create_user(
                username=user_name,
                first_name=first_name,
                last_name=last_name,
                email=email,
                password=password1
            )
            user.is_staff = True
            user.save()
            TrainerRegistration.objects.create(user=user, status=False)
            return redirect('login.html')
    else:
        return render(request, 'trainer_registration.html')

def learn_as_trainer(request):
    user = request.user
    TrainerRegistration.objects.create(user=user, status=False)
    user.is_staff = True
    user.save()
    return render(request, 'learn_as_trainer.html')

SRC/lms/templates/lms/course_basic_details.html
{% extends 'lms/home_base.html' %}
{% block content %}

<section style="margin-top: 100px;" id="team">
  <section class="container">
    <div class="section-header">
      <h3>Enter Course Basic Details:</h3>
      <br>
    </div>
    <center>
      <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <h4>Please Choose a best landing Image for your course!</h4>
        <div class="row">
          <div class="col-md-4"></div>
          <div class="col-md-4">
            <p>{{ form.course_image }}</p>
          </div>
          <div class="col-md-4"></div>
        </div>
        <h4>Enter a best description for your course!</h4>
        <div class="row">
          <div class="col-md-3"></div>
          <div class="col-md-6">
            <p><h5>{{ form.course_desc }}</h5></p>
          </div>
          <div class="col-md-3"></div>
        </div>
        {{ form.user }}
        {{ form.course_info }}
        <input type="submit" class="btn btn-primary">
      </form>
    </center>
  </section>
</section>

{% endblock %}

SRC/lms/templates/lms/course_details.html
{% extends 'lms/home_base.html' %}
{% block content %}

<section style="margin-top: 100px;" id="team">
  <section class="container">
    <div class="section-header">
      <h3><a href="{% url 'lms:course_basic_details' course_slug %}">Course Details</a></h3>
    </div>
  </section>
</section>

{% endblock content %}

SRC/lms/templates/lms/course_info.html
{% extends "base_generic.html" %}

{% block content %}
<section style="margin-top: 100px;" id="team">
  <section class="container">
    <div class="section-header">
      <h3>Enter Course Details:</h3>
      <br>
    </div>
    <center>
      <h4>What could be an interesting title for your course!</h4>
      <h6>It's ok if you can't think of a good title now. You can change it later!</h6>
      <form method="POST" action="{% url 'lms:course_info' %}" enctype="multipart/form-data">
        {% csrf_token %}
        <p>{{ form.course_name }}</p>
        <h4>Which category relates to your course!</h4>
        <p><h5>{{ form.category }}</h5></p>
        {{ form.user }}
        <input type="submit" class="btn btn-primary">
      </form>
    </center>
  </section>
</section>

<br>
<div class="section-header">
  <h3>Courses By You:</h3>
  <br>
</div>
<div class="row">
  {% if course_details %}
  {% for details in course_details %}
  <div class="col-lg-3 col-md-6 wow fadeInUp" data-wow-delay="0.2s">
    <div class="member">
      <img src="{{ details.course_image.url }}" class="" alt="" height="254" width="100%">
      {{ details.course_info.course_name }}
    </div>
  </div>
  {% endfor %}
  {% else %}
  <center><h4>OOps, You haven't created any course yet! Maybe your'e confused that which course I should create first on such an interesting platform!</h4></center>
  {% endif %}
</div>
{% endblock content %}

SRC/lms/templates/lms/dashboard.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Dashboard</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'lms/styles.css' %}">
</head>
<body>
    <header class="container">
        <h1>Dashboard</h1>
        <nav>
            <a href="{% url 'lms:course_details' course_slug='your_course_slug' %}">Course Management</a>
            <a href="#">User Management</a>
            <a href="#">Trainer Applications</a>
            <a href="#">Reports</a>
            <a href="#">Site Settings</a>
            <a href="{% url 'lms:logout' %}" class="logout-btn">Logout</a>
        </nav>
    </header>

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
</body>
</html>

SRC/lms/templates/lms/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Home</title>
    <!-- Load static template tag -->
    {% load static %}
    <!-- Include Bootstrap CSS from CDN -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
    <!-- Include custom CSS file -->
    <link rel="stylesheet" href="{% static 'lms/styles.css' %}">
</head>
<body>
    <div class="container">
        <div class="mainbody">
            <h1 id="welcometext">Welcome!</h1>
            {% if user.is_authenticated %}
                <p>Hello, {{ user.first_name }}</p>
                <a href="{% url 'lms:logout' %}" class="btn btn-primary">Logout</a>
                <a href="{% url 'lms:register_as_trainer' %}" class="btn btn-secondary">Register as Trainer</a>
            {% else %}
                <a href="{% url 'lms:login' %}" class="btn btn-primary">Login</a>
                <a href="{% url 'lms:user_registration' %}" class="btn btn-secondary">SignUp</a>
            {% endif %}
        </div>
    </div>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
</body>
</html>

SRC/lms/templates/lms/home_base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>GKTCS Innovations</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
</head>
<body>
    <div class="container">
        {% if user.is_authenticated %}
            <p>Hello, {{ user.first_name }}</p>
            <a href="{% url 'lms:logout' %}" class="btn btn-primary">Logout</a>
        {% else %}
            <a href="{% url 'lms:login' %}" class="btn btn-primary">Login</a>
            <a href="{% url 'lms:user_registration' %}" class="btn btn-secondary">SignUp</a>
        {% endif %}
    </div>

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
</body>
</html>

SRC/lms/templates/lms/learner_as_trainer.html
{% extends 'lms/home_base.html' %}
{% block content %}

<section style="margin-top: 100px;" id="team">
  <section class="container">
    <div class="section-header">
      <h3>Verification is in Progress!</h3>
    </div>
  </section>
</section>

{% endblock content %}

SRC/lms/templates/lms/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>User Login</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
</head>
<body>
    <div class="container">
        <h2>User Login</h2>
        <form action="{% url 'lms:login' %}" method="POST">
            {% csrf_token %}
            <div class="form-group">
                <label for="user_name">Username:</label>
                <input type="text" id="user_name" name="user_name" class="form-control" required>
            </div>
            <div class="form-group">
                <label for="password">Password:</label>
                <input type="password" id="password" name="password" class="form-control" required>
            </div>
            <button type="submit" class="btn btn-primary">Login</button>
        </form>
        <div>
            {% if messages %}
                {% for message in messages %}
                    <div class="alert alert-{{ message.tags }}">{{ message }}</div>
                {% endfor %}
            {% endif %}
        </div>
    </div>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
</body>
</html>

SRC/lms/templates/lms/trainer_registration.html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta http-equiv="X-UA-Compatible" content="ie=edge">
<title>Trainer Registration</title>
</head>
<body>
<form action="trainer_registration" method="POST">
    {% csrf_token %}
    <input type="text" name="first_name" placeholder="First Name" required><br>
    <input type="text" name="last_name" placeholder="Last Name" required><br>
    <input type="text" name="user_name" placeholder="User Name" required><br>
    <input type="email" name="email" placeholder="email" required><br>
    <input type="text" name="mobile" placeholder="Mobile" required><br>
    <input type="password" name="password1" placeholder="Password" required><br>
    <input type="password" name="password2" placeholder="Confirm Password" required><br>
    <input type="submit">
</form>
<div>
    {% for message in messages %}
    <h3>{{ message }}</h3>
    {% endfor %}
</div>
</body>
</html>

SRC/lms/templates/lms/user_registration.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>User Registration</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
</head>
<body>
    <h2>User Registration</h2>
    <div class="container">
        <form method="POST" action="{% url 'user_registration' %}">
            {% csrf_token %}
            <label for="first_name">First Name:</label>
            <input type="text" id="first_name" name="first_name" class="form-control" required><br>

            <label for="last_name">Last Name:</label>
            <input type="text" id="last_name" name="last_name" class="form-control" required><br>

            <label for="user_name">Username:</label>
            <input type="text" id="user_name" name="user_name" class="form-control" required><br>

            <label for="email">Email:</label>
            <input type="email" id="email" name="email" class="form-control" required><br>

            <label for="mobile">Mobile:</label>
            <input type="text" id="mobile" name="mobile" class="form-control" required><br>

            <label for="password1">Password:</label>
            <input type="password" id="password1" name="password1" class="form-control" required><br>

            <label for="password2">Confirm Password:</label>
            <input type="password" id="password2" name="password2" class="form-control" required><br>

            <button type="submit">Register</button>
        </form>
    </div>

    <div>
        {% for message in messages %}
            <h3>{{ message }}</h3>
        {% endfor %}
    </div>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
</body>
</html>